### PR TITLE
Breaking change to API, but with ear-clipping triangulation.

### PR DESCRIPTION
**Pull request by raspofabs**
Hey, I have tested this with the concave polygon mesh I had, and it now seems to triangulate fine. I hope you find this example useful, but I don't know if you will want to pull it as it changes the API due to wanting to work with vectors to do the triangle checks. Sorry I couldn't easily do it without adding a tiny vertex type and changing the types.

### CODE REVIEW

**Comment by syoyo** [comment]
Cool! I will review it as soon as possible!

**Comment by syoyo** [comment]
I have merged the PR and pushed into `devel` branch.

`devel` branch will become version 2.0.0 after some code cleanups and API re-design considering this issue https://github.com/syoyo/tinyobjloader/issues/141

You can use `devel` for a while for your own project.

**Comment by raspofabs** [comment]
If you're willing to move to vector struct types, may I suggest you add a colour type too? It would make the materials a bit more readable for some people. I understand that this means there is a greater difference between the c and c++ versions than before.

⁣fabs();

**Comment by syoyo** [comment]
Absolutely yes! > color type

PR is always welcome!

**Pull request closed without merging**
