### PR TITLE
Added support for line paths.

### PR DESCRIPTION
**Pull request by ZKing1000**
I needed to be able to import lines from an obj file I exported from blender and was disappointed to see it wasn't supported, so I added support; support for the 'l' character, similar to 'f' character. For more information check wikipedia: https://en.wikipedia.org/wiki/Wavefront_.obj_file#Line_elements

If there are any problems that I could fix than just say so. I hope this is of use to someone else. Thanks!

### CODE REVIEW

**Comment by syoyo** [comment]
Thanks! I'll review & fix build failure soon!

**Comment by ZKing1000** [comment]
Awesome! It compiles and works fine on my machine. I'm not sure why the build is failing...

**Comment by syoyo** [comment]
Unit test fails. for example,

```
-------------------------------------------------------------------------------
norm_texopts
-------------------------------------------------------------------------------
tester.cc:661
...............................................................................
tester.cc:674: FAILED:
  REQUIRE( 1 == shapes.size() )
with expansion:
  1 == 2
```

It now creates invalid(empty?) shape.

**Comment by ZKing1000** [comment]
Could it be because I removed this logic?:

if (faceGroup.empty()) {
   return false;
}

(Starting on line 1024)

**Comment by syoyo** [comment]
Yes. it should not be removed.

And the logic will be

if (faceGroup.empty() && lineGroup.empty()) {
return false;
}

**Comment by syoyo** [comment]
Thanks! merged.

**Pull request merged**
