### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ReinierMaas**
strcutre -> structure

### CODE REVIEW

**Comment by syoyo** [comment]
Thanks! merged.

**Comment by syoyo** [comment]
Opps, its merged into `develop` branch.  Is it correct?(`develop` is not active at this time)

**Comment by ReinierMaas** [comment]
It is the correct README.md.
About that, I do not know which version to use from the repository.
I am building a simple ray-tracer and want to use the vertices from an object file.
What is the best version to use? From master?

**Comment by syoyo** [comment]
Since v1.0.0, `master` is the active and recommended branch. `develop` is now a bit older and not recommended for the use.

**Pull request merged**
