### PR TITLE
ear clipping using pnpoly algorithm

### PR DESCRIPTION
**Pull request by raspofabs**
I noticed a bug with badly selecting the axis. pnpoly required selecting an axis for running against its 2D algorithm. Doing what it suggested turned out to be a bad idea on some geometry, so I fixed it, and now here's a new PR.

### CODE REVIEW

**Comment by syoyo** [comment]
Super cool! Merged!

**Comment by syoyo** [comment]
@raspofabs We found a bug that internal angle test in trinangulation fails in some case: https://github.com/tinyobjloader/tinyobjloader/issues/295 

The situation is 

* (signed) `area` is calculated over the polygon
*  the signedness of `area` become wrong depending on the value of vertex coordinate
*  each angle is falsely detected as internal angle(even for the square polygon)
* `remainingFace.vertex_indices.size()` become 4 or more, resulting some faces become disappear. https://github.com/tinyobjloader/tinyobjloader/blob/9173980d1de273b17eba5e10eb189e8b4be89425/tiny_obj_loader.h#L1575

 Computing signed `area` per triangle seems correctly handle internal angle test. Code is somewhat like this:

```
            real_t e0x = vx[1] - vx[0];
            real_t e0y = vy[1] - vy[0];
            real_t e1x = vx[2] - vx[1];
            real_t e1y = vy[2] - vy[1];
            real_t cross = e0x * e1y - e0y * e1x;

            real_t area = (vx[0] * vy[1] - vy[0] * vx[1]) * static_cast<real_t>(0.5);

            // if an internal angle
            if (cross * area < static_cast<real_t>(0.0)) {
              guess_vert += 1;
              continue;
            }
```

@raspofabs Do you think this is the correct solution?

**Comment by raspofabs** [comment]
> 
> 
> @raspofabs We found a bug that internal angle test in trinangulation fails in some case: #295
> 
> The situation is
> 
>     * (signed) `area` is calculated over the polygon
> 
>     * the signedness of `area` become wrong depending on the value of vertex coordinate
> 
>     * each angle is falsely detected as internal angle(even for the square polygon)
> 
>     * `remainingFace.vertex_indices.size()` become 4 or more, resulting some faces become disappear. https://github.com/tinyobjloader/tinyobjloader/blob/9173980d1de273b17eba5e10eb189e8b4be89425/tiny_obj_loader.h#L1575
> 
> 
> Computing signed `area` per triangle seems correctly handle internal angle test. Code is somewhat like this:
> 
> ```
>             real_t e0x = vx[1] - vx[0];
>             real_t e0y = vy[1] - vy[0];
>             real_t e1x = vx[2] - vx[1];
>             real_t e1y = vy[2] - vy[1];
>             real_t cross = e0x * e1y - e0y * e1x;
> 
>             real_t area = (vx[0] * vy[1] - vy[0] * vx[1]) * static_cast<real_t>(0.5);
> 
>             // if an internal angle
>             if (cross * area < static_cast<real_t>(0.0)) {
>               guess_vert += 1;
>               continue;
>             }
> ```
> 
> @raspofabs Do you think this is the correct solution?

It's been a while, but this doesn't look like the pnpoly solution (the one using a deduced best axis to flatten to a 2D case and not use cross products at all) I rememember adding. The idea if using angles was prone to these errors, maybe I can dig up the old solution and write it into the new codebase.

**Comment by raspofabs** [comment]
> 
> 
> @raspofabs We found a bug that internal angle test in trinangulation fails in some case: #295
> 
> The situation is
> 
>     * (signed) `area` is calculated over the polygon
> 
>     * the signedness of `area` become wrong depending on the value of vertex coordinate
> 
>     * each angle is falsely detected as internal angle(even for the square polygon)
> 
>     * `remainingFace.vertex_indices.size()` become 4 or more, resulting some faces become disappear. https://github.com/tinyobjloader/tinyobjloader/blob/9173980d1de273b17eba5e10eb189e8b4be89425/tiny_obj_loader.h#L1575
> 
> 
> Computing signed `area` per triangle seems correctly handle internal angle test. Code is somewhat like this:
> 
> ```
>             real_t e0x = vx[1] - vx[0];
>             real_t e0y = vy[1] - vy[0];
>             real_t e1x = vx[2] - vx[1];
>             real_t e1y = vy[2] - vy[1];
>             real_t cross = e0x * e1y - e0y * e1x;
> 
>             real_t area = (vx[0] * vy[1] - vy[0] * vx[1]) * static_cast<real_t>(0.5);
> 
>             // if an internal angle
>             if (cross * area < static_cast<real_t>(0.0)) {
>               guess_vert += 1;
>               continue;
>             }
> ```
> 
> @raspofabs Do you think this is the correct solution?

Sorry, my mistake. Yes, it looks like the problem is precision during the area calculation.
A simple fix (imo) would be to subtract the first coordinate from every vertex position before committing to doing the calculations. Then there will always be a vertex at 0,0,0 and the likelihood of precision issues occuring should be vastly reduced.

so, take a vertex at random (first is fine), then subtract that vertex's values from all others before doing analysis of the vertices. I can't work on this at the moment as I don't have a machine set up for development right now.

**Comment by syoyo** [comment]
@raspofabs Thanks!

> A simple fix (imo) would be to subtract the first coordinate from every vertex position before committing to doing the calculations. Then there will always be a vertex at 0,0,0 and the likelihood of precision issues occuring should be vastly reduced.

I see. So compute area over polygon(not per trinagle) based on relative vertex coordinate(e.g. move the first vertex to the origin) would solve the issue. I will try it to implement.

BTW I have integrated mapbox's earcut into tinyobjloader. We can verify the correctness with it: https://github.com/tinyobjloader/tinyobjloader/pull/298

**Comment by syoyo** [comment]
@raspofabs After reading algorithm description of earcut, area is calculated per face, not over the polygon. Precision wasn't a problem.

**Pull request merged**
