### PR TITLE
Used new hashed keywords, buffered file read

### PR DESCRIPTION
**Pull request by tigrazone**
18% - 25% file read speedup,
more clear code,
keywords list

### CODE REVIEW

**Comment by syoyo** [comment]
Super cool! I'll review code and check the reason of build failure as soon as possible.

**Comment by tigrazone** [comment]
please wait. now I want to implement some ideas and after merge when I implement and say. You can read my sources from last commits

**Comment by tigrazone** [comment]
Now I want to refactorize line read and process - rewrite in c-style and minimize chars copy

**Comment by syoyo** [comment]
Firstly, it uses C++11 feature(`unordered_map`). I want keep tinyobjloader `master` C++03 compilable, thus will create `experimental` or `C++11` branch and merge the PR to there.

**Comment by tigrazone** [comment]
so I can use map :-)

**Comment by tigrazone** [comment]
map remake done!
works fast and ok

**Comment by tigrazone** [comment]
now I publish remake with hashed material_map.
from tokens or maretial.name calculate hash val and use it as key.
for red-black trees int compares if faster then string compare.
x31 hash function is good for speed and stability

**Comment by syoyo** [comment]
Cool! > map remake done!

**Comment by syoyo** [comment]
I have merged PR into `tigrazone-master` branch, and there is one error in unit test.

```
-------------------------------------------------------------------------------
pbr
-------------------------------------------------------------------------------
tester.cc:366
...............................................................................

tester.cc:380: FAILED:
  REQUIRE( 0.2 == Approx(materials[0].roughness) )
with expansion:
  0.2 == Approx( 0.0 )
```

Can you please investigate the reason of the failure, @tigrazone ?

**Comment by tigrazone** [comment]
I dont know what a problem. need to read sources. I reply you

**Comment by tigrazone** [comment]
i fix errors. try to retest.
on my computer tests passed ok

**Comment by syoyo** [comment]
When its ready to start merge? Is there further commits planned?

**Comment by tigrazone** [comment]
two days I need to check one idea. I say you when to start merge

**Comment by tigrazone** [comment]
My ideas has no effect.
Please merge with my last commit from my repository

**Comment by syoyo** [comment]
Merged into `tigrazone` branch.

It requires some amount of code refactoring, and also there is slight API change, thus I may merge this together with PR  https://github.com/syoyo/tinyobjloader/pull/151

**Comment by tigrazone** [comment]
ok i'm happy to read this!

**Comment by syoyo** [comment]
I have merged `tigrazone` and https://github.com/syoyo/tinyobjloader/pull/151 into `devel` branch(which will become future v2.0.0). I'll do code refactoring and API cleanup from now on.

**Comment by tigrazone** [comment]
hello! what's new?
when you make release?

**Comment by syoyo** [comment]
> when you make release?

I found it requires some amount of code refactoring, so I can not promise when its ready to be released.

**Pull request closed without merging**
