### PR TITLE
Fixed missing function declaration warning.

### PR DESCRIPTION
**Pull request by aerie94**

### CODE REVIEW

**Comment by syoyo** [comment]
I think just adding `static` keyword to `safeGetLine` should solve the issue.
Which compiler do you use?

**Comment by syoyo** [comment]
Can you try with recent commit?

I have added `static` keyword to safeGeline:  https://github.com/syoyo/tinyobjloader/commit/c7da23795d07b054910ee053bdfe7dd89775cf8f

**Comment by filipwasil** [comment]
Adding a static will generate a warning "function not used" in every compilation unit where the static is added and not used. This will happen for sure, if someone will try to include a "tinyobjloader.h" in header file. It makes possible to compile with pedantic compilers.  I think that function declaration could be better here.

**Comment by syoyo** [comment]
I couldn't reproduce the warning. Please post reproducable procedure.

FYI,

```

**Comment by aerie94** [comment]
I use g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 and compile it with 

`g++ prog.cpp tinyobjloader/tiny_obj_loader.cc -Wmissing-declarations --std=c++11 -o a`

```
#include "tinyobjloader/tiny_obj_loader.h"
int main(int , char *[]) {
return 1;
}
```

**Comment by syoyo** [comment]
> I use g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 and compile it withI have confirmed adding `static` to sageGetline(current recent master) does not show declararion warning.

>  I think @aerie94 approach makes possible to compile with pedantic compilers in all cases and probably will be a better solution in this case.

**Comment by aerie94** [comment]
Ok, if it's not intended to be included in header files, then static is fine here. Cheers.

**Comment by syoyo** [comment]
Thanks for reporting!

**Pull request closed without merging**
